# Stage 1: build
FROM node:22.18-alpine AS build

WORKDIR /app

# COPY package*.json ./
COPY package.json ./
# RUN npm ci
RUN npm install

COPY . .
RUN npm run build

# Stage 2: production
FROM node:22.18-alpine

WORKDIR /app

COPY --from=build /app/dist ./dist

RUN npm install -g serve

EXPOSE 8000

# CMD ["serve", "-s", "dist", "-l", "8000"]
# CMD serve -s dist -l ${PORT:-8000}
CMD serve -s dist -l tcp://0.0.0.0:${PORT:-8000}