#!/usr/bin/env python3
# Status: verified
# Auto-generated by Along for test
import os
import shutil
import subprocess
import sys

def find_repo_root(start_dir=None):
    try:
        from alongkit.repo import find_repo_root as resolver
        return resolver(start_dir)
    except ImportError:
        cur = os.path.abspath(start_dir or os.path.dirname(__file__))
        while True:
            for marker in (".along", ".git", "AGENTS.md"):
                if os.path.exists(os.path.join(cur, marker)):
                    return cur
            parent = os.path.dirname(cur)
            if parent == cur:
                return os.path.abspath(start_dir or os.path.dirname(__file__))
            cur = parent

def main():
    repo_root = find_repo_root(os.path.dirname(__file__))
    base_cmd = ['npm', 'test']
    full_cmd = list(base_cmd) + sys.argv[1:]
    print(f"-> Running: {' '.join(full_cmd)}")
    target = shutil.which(full_cmd[0]) if (os.name == "nt" and full_cmd) else full_cmd[0]
    exec_cmd = [target or full_cmd[0]] + full_cmd[1:]
    res = subprocess.run(exec_cmd, cwd=repo_root)
    sys.exit(res.returncode)

if __name__ == "__main__":
    main()
